### ISSUE TITLE
Proposal: rework client setup and consul_services

### ISSUE THREAD

**Issue by jardleex** [mrlesmithjr/ansible-consul#22]
Hello @mrlesmithjr 

I'd like to rework the way the role does configure consul clients and wanted to have your opinion on that.

Currently the role user needs to name his group of clients in ``consul_clients_group``. Based on that two decisions are made:
1. set the server option to false in the consul config.json
2. include the _app-services.yml_ to define services on a client

Here is what I like to change:
1. The role wont work if the user just includes it on servers without defining the server or clients group. Therefor I'd like to retire the ``consul_clients_group`` completely and simply treat hosts NOT being in ``consul_servers_group`` as clients. This would:

 - simplify the role
 - make it work out of the box
 - allow services also being defined on servers too

2. The role predefines some ``consul_services`` in ``defaults/main.yml`` which most users don't want/need. Here I'd like to unset the variable and move their content into ``playbook.yml`` so the Vagrantbox still uses them for testing and demo purposes.

What do you think on that?
If you're fine with it I'll prepare a PR so you can have a look.

I also recommend to introduce tags/relases on this repo as this and maybe upcoming changes may break the function for users just utilizing the role master.

Best regards

Jard

**Comment by mrlesmithjr** [comment]
@jardleex I like these ideas. Number 1 is something that I had been thinking about already so that is definitely good.

**Comment by jardleex** [comment]
@mrlesmithjr thanks for the feedback. 
I'll begin a PR which covers number 1 for now. Let's see how we may proceed afterwards.

**Comment by jardleex** [comment]
For Nr 2 these two, also combine-able ways are possible.

```
diff --git a/tasks/main.yml b/tasks/main.yml
index 931efc7..4ac71cf 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -20,8 +20,8 @@
   tags:
     - consul-app-services
   when: >
-        ((groups[consul_clients_group] is defined and inventory_hostname
-        in groups[consul_clients_group])) and consul_services is defined
+        consul_services is defined and
+        consul_services
 
 - include: dnsmasq.yml
   when: >
```

This one allows the role user to define ``consul_services: null`` to have no services configured at all.

Additionally the consul_services variable may get moved with it's data from ``defaults/main.yml`` to ``playbook.yml`` to utilize them in Vagrant. This would give the role user the full freedom of not having to override anything but sill being able to set own services.

What do you think?

**Comment by mrlesmithjr** [comment]
I would define as `consul_services: []` to keep that variable there as an identified option. This is something I thought I had already done but apparently in one of my test environments only.

**Comment by mrlesmithjr** [comment]
@jardleex I would also agree that tags should be added. I will begin working on that soon as well.

**Comment by jardleex** [comment]
I'll close this one as all discussed changes have been applied.
Adding tags can happen independently.
